name: <REPOSITORY_NAME>
description:

inputs:
  input_value:
    description: ""
    required: true

outputs:
  output_value:
    description: ""
    value: ${{ steps.result.outputs.output_value }}

runs:
  using: "composite"
  steps:
    - name: Execute shell script
      shell: bash
      id: result
      run: |
        result="$(. ${GITHUB_ACTION_PATH}/main.sh ${{ inputs.version }})"
        echo "output_value=$result" >> $GITHUB_OUTPUT
