name: CI
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # テストケース
        include:
          - value: ""
            expected_result: ""

    steps:
      - uses: actions/checkout@v3

      - name: Execute Composite Action
        id: test_result
        uses: ./
        with:
          input_value: ${{ matrix.value }}

      - name: Assert result
        run: |
          echo "${{ toJSON(steps.test_result.outputs) }}"

          test $result = $expected || \
            { echo "::error expected=$expected,actual=$result::InvalidResult"; exit 1; }
        env:
          result: ${{ steps.test_result.outputs.output_value }}
          expected: ${{ matrix.expected_result }}
